const THREADS = () => {
  return (
    <div className="relative bg-black w-full h-[907px] overflow-hidden text-left text-xs text-gray-300 font-inter">
      <img
        className="absolute top-[0px] left-[0px] w-full h-[466px] object-cover"
        alt=""
        src="/threads-1@2x.png"
      />
      <form className="m-auto mt-24 rounded-[40px] flex flex-col gap-6 p-8 bg-gray-200 w-[400px] [backdrop-filter:blur(40px)] h-[563px] overflow-hidden">
        <b className="text-[16px] font-inter mt-10 text-white text-left">
          Log in with your Instagram account
        </b>
        <input
          className="w-full [border:none] [outline:none] bg-darkslategray  rounded-xl overflow-hidden flex flex-row items-center justify-start py-[27px] px-10 box-border font-inter text-xs text-gray-100"
          placeholder="username, phone or email"
          type="text"
        />
        <input
          className="w-full [border:none] [outline:none] bg-darkslategray  rounded-xl overflow-hidden flex flex-row items-center justify-start py-[23px] px-10 box-border font-inter text-xs text-gray-100"
          placeholder="password"
          type="password"
        />
        <button className="cursor-pointer [border:none] py-[23px] px-[51px] bg-white  rounded-xl w-full h-[70px] overflow-hidden flex flex-row items-center justify-center box-border">
          <div className="relative text-xs capitalize font-inter text-black text-left">
            log in
          </div>
        </button>
        
        <div className="text-xs m-auto capitalize cursor-pointer font-inter text-gray-300 text-left">
          forgot password
        </div>
        <div className=" flex flex-row items-center justify-between">
          <div className="relative box-border w-[170px] h-px border-t-[1px] border-solid border-white" />
          <div className="relative text-xs capitalize font-inter text-white text-left">
            or
          </div>
          <div className="relative box-border w-[170px] h-px border-t-[1px] border-solid border-white" />
        </div>
        <button className="cursor-pointer m-auto py-[23px] px-10 bg-black hover:bg-slate-400 rounded-xl box-border w-[417px] overflow-hidden flex flex-row items-center justify-between border-[1px] border-solid border-gray-300">
          <img
            className="relative w-10 h-10 overflow-hidden shrink-0"
            alt=""
            src="/skilliconsinstagram.svg"
          />
          <div className="relative text-xs capitalize font-inter text-gray-300 text-left">
            continue with instagram
          </div>
          <img
            className="relative w-6 h-6 overflow-hidden shrink-0"
            alt=""
            src="/chevronright.svg"
          />
        </button>
      </form>
      <div className="absolute top-[551px] left-[1251px] capitalize">
        Scan to get the app
      </div>
      <div className="absolute top-[588px] left-[1261px] rounded-[10px] bg-white w-[111px] overflow-hidden flex flex-row items-center justify-center p-[6.297872543334961px] box-border">
        <div className="flex-1 relative h-[98.4px]">
          <div className="absolute top-[0px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[0px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[3.9px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[7.9px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[11.8px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[15.7px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[19.7px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[23.6px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[27.6px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[27.6px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[27.6px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[27.6px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[27.6px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[31.5px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[35.4px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[39.4px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[43.3px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[47.2px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[27.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[51.2px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[27.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[55.1px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[27.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[59px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[27.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[63px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[66.9px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[70.8px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[51px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[74.8px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[78.7px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[70.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[82.7px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[35.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[43.1px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[86.6px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[58.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[74.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[78.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[86.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[90.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[90.5px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[-0.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[3.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[7.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[11.6px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[15.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[19.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[23.4px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[31.3px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[39.2px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[47px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[54.9px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[62.8px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[66.7px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[82.5px] bg-black w-[3.9px] h-[3.9px]" />
          <div className="absolute top-[94.5px] left-[94.3px] bg-black w-[3.9px] h-[3.9px]" />
        </div>
      </div>
    </div>
  );
};

export default THREADS;
